# Generated by Django 5.1.3 on 2024-11-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='televisionshow',
            options={'ordering': ['release_date'], 'verbose_name': 'Television Show', 'verbose_name_plural': 'Television Shows'},
        ),
        migrations.AlterField(
            model_name='televisionshow',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a short description of the show.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='televisionshow',
            name='genre',
            field=models.CharField(choices=[('drama', 'Drama'), ('comedy', 'Comedy'), ('thriller', 'Thriller')], help_text='Select the genre.', max_length=200, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='televisionshow',
            name='release_date',
            field=models.DateField(help_text='Enter the original release date of the show.', verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='televisionshow',
            name='title',
            field=models.CharField(help_text='Enter the title of the television show.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='televisionshow',
            unique_together={('title',)},
        ),
        migrations.AddIndex(
            model_name='televisionshow',
            index=models.Index(fields=['genre'], name='myapp_telev_genre_392af1_idx'),
        ),
        migrations.AddIndex(
            model_name='televisionshow',
            index=models.Index(fields=['release_date'], name='myapp_telev_release_cded83_idx'),
        ),
    ]
